from __future__ import annotations

import math
import pathlib


PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = PROJECT_ROOT / "Core" / "Src" / "nav_sine_q15.c"


def main() -> None:
    values = [round(math.sin(math.radians(index / 10.0)) * 32768.0) for index in range(901)]
    lines = [
        '#include "nav_sine_q15.h"',
        "",
        "/* Generated by Tools/generate_nav_sine_table.py. */",
        "const uint16_t g_nav_sine_q15[NAV_SINE_Q15_TABLE_SIZE] = {",
    ]
    for start in range(0, len(values), 12):
        chunk = values[start : start + 12]
        suffix = "," if start + len(chunk) < len(values) else ""
        lines.append("    " + ", ".join(f"{value}U" for value in chunk) + suffix)
    lines.append("};")
    lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
