import {mountPreparation} from './route-preparation.mjs?v=bridge-1';
import {commands,buildCommand,frameCommand,describeReply,moduleForWire} from './protocol.mjs?v=heading-hold-1';
import {SerialLink} from './serial.mjs?v=bridge-1';
import {BridgeLink,readOnlyCommand} from './bridge.mjs?v=bridge-1';
import {mountMap} from './map-view.mjs?v=bridge-1';
import {mountQr} from './qr-panel.mjs?v=bridge-1';
const $=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const titles={arm:'机械臂与夹爪',chassis:'底盘',vision:'视觉任务',qr:'二维码',map:'地图与遥测',system:'系统与标定'};
const storageKey='sky-atelier-v1';let prefs={};try{prefs=JSON.parse(localStorage.getItem(storageKey)||'{}')||{};}catch{}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(prefs));}catch{toast('本机存储已满，设置未保存。');}}
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
let active='arm',axis='base',mapView,qrView,prepView,txCount=0,rxCount=0,filter='ALL',logs=[],unseen=0,errors=0,sending=false;
const status=new Map(),forms=[],pages={};
const defaultFavorites=[{label:'设备信息',wire:'info'},{label:'机械臂状态',wire:'state all'},{label:'夹爪打开',wire:'grip open'},{label:'夹爪夹取',wire:'grip catch'}];
let favorites=Array.isArray(prefs.favorites)?prefs.favorites.filter(f=>{try{if(typeof f.label!=='string')return false;frameCommand(f.wire);return true;}catch{return false;}}).slice(0,24):defaultFavorites;
function appendLog(direction,text){const owner=moduleForWire(text);logs.push({time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),direction,text,owner});if(logs.length>500)logs.shift();if(direction==='TX')txCount++;if(direction==='RX')rxCount++;if(text.startsWith('ERR'))errors++;if(!$('autoscroll').checked)unseen++;renderLogs();}
function renderLogs(){const scroll=$('terminal').scrollTop;const scope=$('log-module').value;const entries=logs.filter(l=>(filter==='ALL'||l.direction===filter)&&(scope==='all'||l.owner===(scope==='current'?active:scope)||l.direction==='SYS'));const fragment=document.createDocumentFragment();for(const l of entries){const row=node('div',undefined,`log-entry ${l.direction.toLowerCase()} ${l.text.startsWith('ERR')?'error':''}`);row.append(node('time',l.time),node('b',l.direction),node('span',l.text));fragment.append(row);}if(!entries.length)fragment.append(node('p','本模块尚无收发记录，可切换“全部模块”查看。','empty-log'));$('terminal').replaceChildren(fragment);$('log-count').textContent=`${logs.length}${errors?' · 错误 '+errors:''}`;$('tx-count').textContent=txCount;$('rx-count').textContent=rxCount;$('terminal').scrollTop=$('autoscroll').checked?$('terminal').scrollHeight:scroll;$('new-logs').hidden=!unseen;$('new-logs').textContent=`${unseen} 条新记录 · 恢复跟随`;}
let transport='bridge',link,connectionState='disconnected';
function receive(line){appendLog('RX',line);mapView?.receive(line);qrView?.receive(line);prepView?.receive(line);const owner=moduleForWire(line);if(owner!=='manual'&&!line.startsWith('@CHASSIS ')&&/^(OK |ERR |\[IMU CAL\]|EVT qr )/.test(line)){status.set(owner,{line,time:Date.now(),live:link.connected});renderStatus();}}
function connection(state){connectionState=state;const connected=state==='connected';mapView?.connection(connected);qrView?.connection(connected);prepView?.connection(connected);$('connection-status').textContent=({connected:transport==='bridge'?'本地服务已连接 COM23':'浏览器直连已连接',connecting:transport==='bridge'?'正在连接 COM23…':'正在选择串口…',disconnecting:'正在断开…',disconnected:'尚未连接'})[state];$('connection-dot').classList.toggle('online',connected);$('connect').disabled=state!=='disconnected';$('disconnect').disabled=!connected;$('baud').disabled=state!=='disconnected';$('transport').disabled=state!=='disconnected';for(const value of status.values())value.live=false;if(!connected)$('subscription-note').textContent='';updateControls();renderStatus();if(connected)appendLog('SYS','已连接，尚未自动发送任何指令。');}
function communicationError(error){appendLog('SYS',`通信异常：${error.message}`);toast(error.message);prepView?.refreshConfiguration();updateControls();}
function stopped(){return transport==='bridge'&&bridge.stopLatched;}
function bridgeEvent(e){if(transport!=='bridge')return;if(e.kind==='preparation'&&e.active===false&&e.owner===bridge.preparationOwner&&prepView?.busy)prepView.cancel('共享准备锁定已结束，请重新准备。');if(e.kind==='tx')appendLog('TX',e.text);if(e.kind==='system')appendLog('SYS',e.text||e.error||'本地服务状态变化');if(e.kind==='stop'){if(e.latched)prepView?.cancel('停止已锁定，准备已取消；解除锁定后也不会自动继续。');$('stop-status').textContent=e.latched?({requested:'正在提交停车请求',sent:'停车请求已发出，等待设备回复',accepted:e.tx_complete?'停车发送完成，等待四轮反馈确认':'请求已受理，等待停车发送完成',confirmed:'四轮反馈已确认停车',timeout:'停车确认超时，请检查实车',disconnected:'连接已断开，无法确认停车'})[e.status]||'停止已锁定，等待停车确认':e.status==='idle'?'本地服务就绪 · CMD Ctrl+C 请求停车':'停止锁定已解除 · 任务不会自动继续';$('resume-stop').hidden=!e.latched;updateControls();prepView?.refreshConfiguration();}}
const bridge=new BridgeLink({receive:line=>{if(transport==='bridge')receive(line);},state:state=>{if(transport==='bridge')connection(state);},error:communicationError,event:bridgeEvent,configuration:()=>prepView?.refreshConfiguration()});
const direct=new SerialLink({receive,state:connection,error:communicationError});link=bridge;
const preparationStop=wire=>/^(?:chassis (?:stop|route cancel)|stop (?:all|base|z|x)|vision stop|material stop)$/.test(wire);
function mayQuery(wire){return readOnlyCommand(wire)&&(!prepView?.busy||!prepView.pending);}
async function requestStop(){prepView?.cancel('已中止准备并请求停车；请查看停止状态。');try{if(transport==='bridge')await bridge.stop();else return await send('chassis stop');return true;}catch(error){communicationError(error);return false;}}
async function send(wire,fromPreparation=false){
  if(transport==='bridge'&&['chassis stop','wheel stop'].includes(wire)){return requestStop();}
  if(stopped()&&!readOnlyCommand(wire)){toast('停止已锁定，请确认停车后解除锁定。');return false;}
  if(prepView?.busy&&!fromPreparation){if(preparationStop(wire)||wire==='imu cal cancel')prepView.cancel('已中止准备；实际停止请查看设备反馈。');else if(!mayQuery(wire)){toast('准备正在等待专属回复，请稍后查询，或先取消准备。停止始终可用。');return false;}else prepView.cancel('已退出准备并读取状态，避免查询回复混入准备流程。');}
  if(sending&&!fromPreparation){toast('上一条指令仍在发送，本次未排队。');return false;}
  try{frameCommand(wire);sending=Number(sending)+1;updateControls();await link.send(wire,fromPreparation);if(transport==='direct')appendLog('TX',wire);toast(`已发送：${wire}`);if(wire==='chassis stream off')$('subscription-note').textContent='已请求关闭遥测';return true;}catch(error){appendLog('SYS',error.message);toast(error.message);return false;}finally{sending=Math.max(0,Number(sending)-1);updateControls();}
}
function canSend(wire){return link.connected&&!sending&&(!stopped()||readOnlyCommand(wire))&&(!prepView?.busy||preparationStop(wire)||wire==='imu cal cancel'||mayQuery(wire));}
function updateControls(){qrView?.refreshControls();document.querySelectorAll('[data-send]').forEach(b=>{const wire=b.dataset.stop||b.title||'';b.disabled=!canSend(wire)||(b.dataset.single==='1'&&axis==='all');});$('raw-send').disabled=!link.connected||!!sending||(!!prepView?.busy&&!!prepView.pending);$('device-info').disabled=!canSend('info');$('service-stop').disabled=transport==='bridge'?!bridge.available:!link.connected;$('resume-stop').disabled=!bridge.available;for(let i=forms.length-1;i>=0;i--){if(forms[i].root.isConnected)forms[i].update();else forms.splice(i,1);}}
async function directServiceCheck(){
  let status;try{status=await bridge.api('status');bridge.available=true;bridge.token=status.token;bridge.config=status.config;}catch{bridge.available=false;}
  prepView?.refreshConfiguration();if(status?.connected)throw new Error('本地服务仍持有串口，请先断开服务连接。');
}
$('connect').onclick=async()=>{if(connectionState!=='disconnected')return;connection('connecting');try{if(transport==='direct'){await directServiceCheck();if(!navigator.serial)throw new Error('请用桌面 Chrome / Edge 打开本地控制台。');}else if(!bridge.available)await bridge.attach();await link.connect(navigator.serial,Number($('baud').value));}catch(error){connection(link.connected?'connected':'disconnected');toast(error.name==='NotFoundError'?'已取消选择串口。':error.message);}};
$('transport').onchange=async()=>{if(connectionState!=='disconnected'||link.connected){$('transport').value=transport;toast('请先断开当前连接再切换连接方式。');return;}const next=$('transport').value;if(next==='direct'){try{await directServiceCheck();}catch(error){$('transport').value=transport;toast(error.message);return;}bridge.suspend();transport='direct';link=direct;$('stop-status').textContent='浏览器直连备用模式：CMD 的 Ctrl+C 无法停止此连接';$('resume-stop').hidden=true;}else{transport='bridge';link=bridge;void bridge.start();}connection('disconnected');};$('disconnect').onclick=()=>void link.disconnect().catch(error=>toast(error.message));window.addEventListener('pagehide',()=>{bridge.suspend();if(transport==='direct')void direct.disconnect().catch(()=>{});});$('device-info').onclick=()=>void send('info');$('service-stop').onclick=()=>void requestStop();$('resume-stop').onclick=()=>void bridge.resume().catch(communicationError);
function renderStatus(){const s=status.get(active);$('reply-title').textContent=s?`${s.live?'':'历史 · '}${describeReply(s.line)}`:(link.connected?'已连接 · 请读取状态':'尚未连接');$('reply-text').textContent=s?.line||'状态由设备回复确认，点击按钮不会预先标为成功。';$('reply-time').textContent=s?`最近回复 ${new Date(s.time).toLocaleTimeString('zh-CN',{hour12:false})}`:'尚无本模块回复';}
function definition(id){const c=commands.find(c=>c.id===id);if(!c)throw new Error(`缺少命令定义 ${id}`);return c;}
function action(id,label,preset={},useAxis=false){const c=definition(id),b=node('button',label||c.label);b.type='button';b.dataset.send='1';if(useAxis&&!c.fields.find(f=>f.key==='axis')?.options?.some(([v])=>v==='all'))b.dataset.single='1';const wire=()=>buildCommand(id,{...Object.fromEntries(c.fields.map(f=>[f.key,f.value])),...preset,...(useAxis?{axis}: {})});const hint=()=>{try{b.title=wire();}catch{b.title='请选择单轴';}};b.onmouseenter=hint;b.onfocus=hint;hint();b.onclick=()=>{try{void send(wire());}catch(e){toast(e.message);}};return b;}
function actions(container,list){const row=node('div',undefined,'actions');for(const item of list)row.append(action(...(Array.isArray(item)?item:[item])));container.append(row);return row;}
function controlForm(id,{sharedAxis=false,label}={}){const c=definition(id),root=node('form',undefined,'control-form');root.append(node('h3',label||c.label));const fields=node('div',undefined,'fields'),inputs={};for(const f of c.fields){if(sharedAxis&&f.key==='axis')continue;const wrap=node('label',f.label);let input;if(f.options){input=node('select');if(f.value===''){const placeholder=node('option','请选择（需人工确认）');placeholder.value='';input.append(placeholder);}for(const [v,t] of f.options){const o=node('option',t);o.value=v;input.append(o);}}else{input=node('input');input.type='number';input.min=f.min;input.max=f.max;input.step=f.step??1;input.required=true;}input.name=f.key;input.value=f.value??'';input.id=`${id}-${f.key}`;wrap.append(input);fields.append(wrap);inputs[f.key]=input;}root.append(fields);const note=node('p',c.note||'每次执行发送一条指令，以设备回复为准。','form-note');root.append(note);const preview=node('div',undefined,'preview'),code=node('code'),buttons=node('div',undefined,'form-actions'),copy=node('button','复制'),star=node('button','☆ 常用'),execute=node('button',id==='pos'?'执行相对运动':'执行','primary');copy.type=star.type='button';execute.type='submit';buttons.append(copy,star,execute);preview.append(code,buttons);const validation=node('p','','validation');validation.setAttribute('aria-live','polite');root.append(preview,validation);let wire='';function update(){try{wire=buildCommand(id,{...Object.fromEntries(Object.entries(inputs).map(([k,e])=>[k,e.value])),...(sharedAxis?{axis}: {})});code.textContent=wire;validation.textContent='';execute.disabled=!canSend(wire);copy.disabled=star.disabled=false;}catch(e){wire='';code.textContent='请补全有效参数';validation.textContent=e.message;execute.disabled=copy.disabled=star.disabled=true;}if(inputs.seconds&&['chassis-run','chassis-heading'].includes(id)){const t=Number(inputs.seconds.value);note.textContent=`起步 0.5 秒 + 保持 ${Number.isFinite(t)?t:'—'} 秒 + 停车 0.5 秒，总时长 ${Number.isFinite(t)?Math.round((t+1)*1000)/1000:'—'} 秒。${c.note||''}`;}}for(const input of Object.values(inputs)){input.oninput=update;input.onchange=update;}root.onsubmit=e=>{e.preventDefault();update();if(wire)void send(wire);};copy.onclick=()=>void copyText(wire);star.onclick=()=>addFavorite(c.label,wire);forms.push({root,update});update();return root;}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('已复制。');}catch{toast('无法复制，请手动选择文本。');}}
function advanced(container,title,ids){const details=node('details',undefined,'advanced');details.append(node('summary',title));const selector=node('select');selector.setAttribute('aria-label',title);const placeholder=node('option','选择调试操作');placeholder.value='';selector.append(placeholder);for(const id of ids){const c=definition(id),o=node('option',c.label);o.value=id;selector.append(o);}const target=node('div');selector.onchange=()=>{target.replaceChildren();if(selector.value){const c=definition(selector.value);if(c.fields.length)target.append(controlForm(c.id,{sharedAxis:c.fields.some(f=>f.key==='axis')}));else actions(target,[c.id]);}updateControls();};details.append(selector,target);container.append(details);}
function tabs(container,items){const nav=node('div',undefined,'mode-tabs'),body=node('div');const buttons=[];for(const [title,render] of items){const b=node('button',title);b.type='button';b.onclick=()=>{buttons.forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});body.replaceChildren();render(body);updateControls();};nav.append(b);buttons.push(b);}container.append(nav,body);buttons[0].click();}
function buildPages(){for(const key of Object.keys(titles).filter(x=>x!=='map')){pages[key]=node('div');pages[key].dataset.page=key;pages[key].hidden=true;$('module-content').append(pages[key]);}
const arm=pages.arm;arm.append(node('small','当前对象'));const picker=node('div',undefined,'axis-picker');for(const [value,label] of [['base','底座 Base'],['z','升降 Z'],['x','伸缩 X'],['all','全部轴']]){const b=node('button',label);b.classList.toggle('active',value===axis);b.setAttribute('aria-pressed',String(value===axis));b.onclick=()=>{axis=value;picker.querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});updateControls();};picker.append(b);}arm.append(picker);actions(arm,[['enable','使能',{},true],['disable','失能',{},true],['state','读取状态',{},true],['stop','停止所选轴',{},true],['position','读取位置',{},true]]);arm.append(controlForm('pos',{sharedAxis:true}));const grip=node('div',undefined,'grip-row');grip.append(node('h3','夹爪'));actions(grip,[['grip-open','打开'],['grip-catch','夹取']]);arm.append(grip);advanced(arm,'回零、零点与运动参数',['home','origin','zero','config-get','config-set']);advanced(arm,'夹爪调试',['grip-idle','grip-duty']);
const ch=pages.chassis;actions(ch,[['chassis-task','读取任务状态'],['chassis-stop','停止底盘']]);tabs(ch,[['自动保向 / 转向',body=>body.append(controlForm('chassis-run'))],['保持模块航向',body=>{body.append(node('p','目标是 HWT101 模块角度，不是地图角度。需要本次 IMU 验证通过并已设置地图锚点。','form-note'));body.append(controlForm('chassis-heading'));}]]);advanced(ch,'位置、单轮与旧速度测试',['move','velocity','wheel','wheel-stop','chassis-hold','chassis-status']);advanced(ch,'反馈、单位与地图锚点',['feedback-read','feedback-select','feedback-on','feedback-off','profile','units','chassis-origin','reset-confirmed']);
const realRoute=node('section',undefined,'real-route-panel');realRoute.id='real-route-panel';realRoute.append(node('h2','实车前四段测试'));
realRoute.append(node('p','从 (2250,150,90°) 开始，依次到 (2100,300)、(2100,1200)、(2100,2100)、(1200,2100)。MCU 以 50 mm/s 反馈定距执行当前一段并停车；每段停止后，由你点击下一段。','form-note'));
actions(realRoute,[['chassis-route-start','开始第 1 段'],['chassis-route-next','手动下一段'],['chassis-route-cancel','取消路线'],['chassis-route-status','查询实车路线']]);
const realStatus=node('pre','实车路线状态不可用 · 请在地图页手动开启遥测；查询回复见收发记录。','real-route-status');realStatus.id='real-route-status';realStatus.setAttribute('role','status');realRoute.append(realStatus);
prepView=mountPreparation({root:realRoute,send:wire=>send(wire,true),beginTelemetry:nonce=>mapView.beginPreparedTelemetry(nonce),telemetry:()=>mapView?.snapshot(),getConfig:()=>bridge.config,saveConfig:c=>bridge.saveConfig(c),configAvailable:()=>bridge.available,isStopped:stopped,acquire:()=>transport==='bridge'?bridge.acquirePreparation():Promise.resolve(),release:()=>bridge.releasePreparation(),changed:updateControls});
realRoute.append(controlForm('chassis-move'));realRoute.append(node('p','需先完成驱动反馈配置、IMU 验证与地图锚点设置。路线到点表示编码器反馈估计进入容差，不能替代视觉精对准、扫码或抓取确认。刷新、重连和切换页面不会开始或进入下一段；取消请求与实际停止分别看设备状态。','form-note'));
const telemetryLink=node('a','前往地图与遥测，手动开启状态订阅');telemetryLink.href='#map';realRoute.append(telemetryLink);ch.prepend(realRoute);
tabs(pages.vision,[['任务执行',body=>{body.append(node('p','Base 回零 → 内部请求识别 → 底盘搜索 → 底盘/X 对准。当前终点为对准完成。','form-note'));actions(body,[['material-status','读取任务状态'],['material-stop','停止物料任务']]);body.append(controlForm('material-auto'));}],['相机调试',body=>{body.append(node('p','仅识别，不主动驱动机构；停止识别请求不等于停止物料任务。','form-note'));actions(body,[['camera-status','读取相机状态'],['camera-stop','停止识别请求']]);body.append(controlForm('camera-material'));}],['标定与分步测试',body=>{actions(body,[['vision-status','读取 Base/X 状态'],['vision-stop','停止 Base/X 对准']]);advanced(body,'参考与两种标定路径',['vision-ref','vision-calib-material','vision-calib-chassis']);body.append(controlForm('vision-material',{label:'Base/X 独立对准'}));}]]);
const sys=pages.system;actions(sys,[['info','设备信息'],['help','固件帮助'],['imu-status','读取 IMU 状态']]);sys.append(node('p','原生零偏标定约 20 秒，随后自动验证 30 秒；全过程保持静止。保存请求与断电保持验证分别查看。','form-note'));actions(sys,[['imu-cal-start','原生标定'],['imu-verify','验证 10 秒'],['imu-cal-cancel','取消标定/验证']]);advanced(sys,'IMU 连续角度输出',['imu-stream-on','imu-stream-off']);
qrView=mountQr({root:pages.qr,send,notify:toast,canSend});}
function addFavorite(label,wire){if(!wire)return;if(favorites.some(f=>f.wire===wire)){toast('此命令已在常用中。');return;}if(favorites.length>=24){toast('最多保留 24 条常用，请先移除。');return;}favorites.push({label,wire});prefs.favorites=favorites;save();renderFavorites();toast('已加入常用。');}
function renderFavorites(){const shown=favorites.map((f,index)=>({...f,index,owner:moduleForWire(f.wire)})).filter(f=>f.owner===active||f.owner==='manual');$('favorites-count').textContent=`${shown.length} 项 · 点击即发送`;$('favorites').replaceChildren(...shown.map(f=>{const box=node('div',undefined,'favorite'),b=node('button',`${f.owner==='manual'?'手动 · ':''}${f.label}`),remove=node('button','×','remove');b.dataset.send='1';b.title=f.wire;b.append(node('code',f.wire));b.onclick=()=>void send(f.wire);remove.setAttribute('aria-label',`移除 ${f.label}`);remove.onclick=()=>{favorites.splice(f.index,1);prefs.favorites=favorites;save();renderFavorites();};box.append(b,remove);return box;}));updateControls();}
function route(){const key=location.hash.slice(1);active=titles[key]?key:'arm';$('map-page').hidden=active!=='map';$('console-page').hidden=active==='map';document.body.classList.toggle('map-active',active==='map');for(const [key,page] of Object.entries(pages))page.hidden=key!==active;document.querySelectorAll('#navigation a').forEach(a=>a.setAttribute('aria-current',a.hash===`#${active}`?'page':'false'));$('module-title').textContent=titles[active];$('module-badge').textContent=active==='qr'?'任务码接收':'手动操作';renderFavorites();renderStatus();renderLogs();}
$('raw-form').onsubmit=async e=>{e.preventDefault();const command=$('raw-command').value.trim();if(await send(command))$('raw-command').value='';};document.querySelectorAll('[data-stop]').forEach(b=>{b.dataset.send='1';b.onclick=()=>void send(b.dataset.stop);});
$('log-filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderLogs();};$('log-module').onchange=renderLogs;$('clear-log').onclick=()=>{logs=[];txCount=rxCount=unseen=errors=0;renderLogs();};$('terminal').onscroll=()=>{if($('terminal').scrollHeight-$('terminal').clientHeight-$('terminal').scrollTop>25)$('autoscroll').checked=false;};$('autoscroll').onchange=()=>{if($('autoscroll').checked)unseen=0;renderLogs();};$('new-logs').onclick=()=>{$('autoscroll').checked=true;unseen=0;renderLogs();};$('terminal-toggle').onclick=()=>{const collapsed=$('terminal-panel').classList.toggle('collapsed');$('terminal-toggle').textContent=collapsed?'展开':'收起';$('terminal-toggle').setAttribute('aria-expanded',String(!collapsed));};
$('export-log').onclick=()=>{const content=logs.map(l=>`[${l.time}] ${l.direction} ${l.text}`).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/plain;charset=utf-8'}));const a=node('a');a.href=url;a.download=`yachiyo-${Date.now()}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function applyTheme(){document.body.classList.toggle('dark',prefs.dark===true);$('theme-toggle').textContent=prefs.dark?'◐ 浅色':'◐ 深色';}function appearance(show){$('appearance').hidden=!show;$('appearance-toggle').setAttribute('aria-expanded',String(show));if(!show)$('appearance-toggle').focus();}function applyBackground(){const image=typeof prefs.background==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(prefs.background)?prefs.background:null;document.querySelector('.wallpaper').style.backgroundImage=image?`url("${image}")`:'';const opacity=Number.isFinite(prefs.opacity)?Math.max(0,Math.min(100,prefs.opacity)):85;$('background-opacity').value=opacity;document.documentElement.style.setProperty('--bg-opacity',opacity/100);}
$('theme-toggle').onclick=()=>{prefs.dark=!prefs.dark;save();applyTheme();};$('appearance-toggle').onclick=()=>appearance($('appearance').hidden);$('appearance-close').onclick=()=>appearance(false);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('appearance').hidden)appearance(false);});$('background-opacity').oninput=e=>{prefs.opacity=Number(e.target.value);applyBackground();};$('background-opacity').onchange=save;$('background-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){toast('请选择 2 MB 以内的 PNG/JPEG/WebP。');e.target.value='';return;}try{prefs.background=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});save();applyBackground();}catch{toast('图片读取失败。');}};$('background-reset').onclick=()=>{delete prefs.background;prefs.opacity=85;save();applyBackground();$('background-file').value='';};
applyTheme();applyBackground();buildPages();mapView=mountMap({send,isPreparing:()=>!!prepView?.busy||stopped(),onStatus:text=>$('subscription-note').textContent=text});window.addEventListener('hashchange',route);route();qrView.connection(false);updateControls();appendLog('SYS','八千代·巡航已就绪，默认由本地服务独占 COM23；刷新不会发送指令。');

void bridge.start();
