<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Lds50cHost.Core\Lds50cHost.Core.csproj" />
    <Reference Include="System.IO.Ports">
      <HintPath>..\..\lib\System.IO.Ports.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
